apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: secure-shop
  name: secure-shop
  namespace: secure-shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secure-shop
  template:
    metadata:
      labels:
        app: secure-shop
    spec:
      containers:
      - image: nykiee/my-private-repo
        imagePullPolicy: Always
        name: secure-shop
        ports:
        - containerPort: 8070
      imagePullSecrets:
      - name: dockerhubsecret
